#!/bin/bash

# -e: コマンドが失敗した時点でスクリプト全体を即座にエラー終了する
# -u: 初期化していない変数があるとエラーにしてくれる
# -x: 実行するコマンドを出力してくれる
set -eux

bin=`pwd`/install

if [ "$(uname -m)" = "arm64" ]; then
  curl https://dot.kaz.dev/install_aarch64-apple-darwin -o $bin
elif [ "$(uname -m)" = "x86_64" ]; then
  curl https://dot.kaz.dev/install_x86_64-apple-darwin -o $bin
else
  echo "Unsupported architecture"
  exit 1
fi

chmod +x $bin
$bin
if [ $? = 0]; then
  rm $bin
fi
