name: build

on:
  push

permissions:
  contents: write

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - name: Compile install binary
        run: deno task compile:mac
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            install
